### ISSUE TITLE
Please explain how to use.

### ISSUE THREAD

**Issue by firestarter7924** [soroushmirzaei/telegram-configs-collector#1]
Hello. Thanks for your job but personally I can't understand how to use links. For what they are? What software should i use?
Have tried to import some subscriptions into the V2RayNG client but it can't understand what is this.

**Comment by soroushmirzaei** [comment]
To use the subscription links, you could install any client based on xray-core or singbox on your devices. Then it just requires to create subscriptuon type group in the app and enter each of the subscription links in the app and update the group. By this way the configurations would be imported directly from the links. you could even schedule updating the group in some of the apps such as NekoBox for android and NekoRay for Windows and Linux operating systems.
I suggest you using NekoBox and NekoRay instead.
