### ISSUE TITLE
Country emojis

### ISSUE THREAD

**Issue by demarcush** [soroushmirzaei/telegram-configs-collector#3]
It would be best to replace 🌎, 🌏 with appropriate country's emoji for better filter-ability by the clients.

> `🔒 VL-WS-TLS 🌎 US-23.158.72.133:443 📡 PING-052.97-MS` to `🔒 VL-WS-TLS 🇺🇸 US-23.158.72.133:443 📡 PING-052.97-MS`

**Comment by soroushmirzaei** [comment]
This feature has been applied and replaced country emoji instead.
Thanks for your kindness and good opinion.
