### ISSUE TITLE
new additional resource for sub link 

### ISSUE THREAD

**Issue by Graveyard9988** [soroushmirzaei/telegram-configs-collector#6]
https://github.com/Leon406/jsdelivr/blob/master/subscribe/subpool2

**Comment by soroushmirzaei** [comment]
تشکر از لطف شما
باید بین موارد بررسی کنم که کدام ساب لینک ها برای کشور ایران مناسب هست و بروزرسانی انجام میشه
چون در غیر اینصورت فرایند بررسی گره ها برای اجرا در هر ساعت زمان بر خواهد بود
