### ISSUE TITLE
درخواست مجوز برای استفاده عمومی

### ISSUE THREAD

**Issue by barry-far** [soroushmirzaei/telegram-configs-collector#8]
سلام وقتت بخیر و ممنون بابت کانفیگ های رایگانی که برای مردم قرار میدی.
ازت میخواستم اجازه بگیرم که لینک سابسکریپشنت رو به رپوزیتوری مخزن خودم اضافه کنم تا مردم بیشتری بتونن از این کانفیگ ها بهره مند بشن...

لینک پروژه بنده : https://github.com/barry-far/V2ray-Configs

**Comment by soroushmirzaei** [comment]
درود و خسته نباشید خدمت شما
خواهش میکنم اختیار دارید. ریپازیتوری کاملا عمومی هست. بله میتونید در پروژه خودتون استفاده کنید

**Comment by soroushmirzaei** [comment]
درود و خسته نباشید خدمت شما
خواهش میکنم اختیار دارید. ریپازیتوری کاملا عمومی هست. بله میتونید در صورت امکان با ذکر منبع در پروژه خودتون استفاده کنید

**Comment by barry-far** [comment]
پروژه بنده هم کاملا اوپن سورس هست و داخل فایل `app.py` لینک شما هست.
اگر توییتر دارید ، آیدیتون رو بگید حتما تگ میکنمتون. 💯

**Comment by soroushmirzaei** [comment]
سپاس از لطف نگاهتون. جسارتا اگر که مقدور هست خود ریپازیتوی یا پروفایل گیت هاب رو رفرنس دهی بفرمایید. در غیر اینصورت از از ایدی توییتر که ذیلا گذاشته شده استفاده بفرمایید.
`@sydsrsmrz`
