### ISSUE TITLE
Unable to update subscriptions

### ISSUE THREAD

**Issue by hjchjchjc4352** [soroushmirzaei/telegram-configs-collector#9]
Unable to update the subscription for the US（https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/countries/us/mixed） region in OpenClash, but subscriptions for other countries like Japan, South Korea, and Singapore are working fine.
Is it a configuration issue on my end, or does OpenClash not support it?

**Comment by soroushmirzaei** [comment]
you could check it out on your browser, it works fine for me on both `NekoBox` and `Nekoray`. notice that the subscription links includes configs in encoded mode `base64`, so be sure that the installed client on your device supports the encoded subscription links.
